/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import com.mycompany.studentmanagementsystem.DBcon;
import java.awt.BorderLayout;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.*;
import java.sql.*;
import java.util.HashMap;
import java.util.Map;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.swing.JRViewer;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author binit
 */
public class branchReports extends javax.swing.JFrame {

    /**
     * Creates new form branchReports
     */
    public branchReports() {
        initComponents();
        btnback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back_black.png")));
        setExtendedState(JFrame.MAXIMIZED_BOTH);
         try{
             DBcon db = DBcon.getInstance();
            Connection con = db.getConnection();
           
            Statement stmt=con.createStatement();
            ResultSet rs=stmt.executeQuery("SELECT branchName FROM branch");
            
            //populating combobox with retrieved branch names
            while(rs.next()){
                CBbranch.addItem(rs.getString("branchName"));
            }
          }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "SQL error","error",JOptionPane.ERROR_MESSAGE);
        }
         
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Error Occured"+ex.toString(),"error",JOptionPane.ERROR_MESSAGE);
        }
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        CBbranch = new javax.swing.JComboBox<>();
        btnbrnchrep = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnback = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Select Branch");

        btnbrnchrep.setText("View Report");
        btnbrnchrep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbrnchrepActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 539, Short.MAX_VALUE)
        );

        btnback.setBackground(new java.awt.Color(242, 242, 242));
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(295, 295, 295)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CBbranch, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(btnbrnchrep)
                .addContainerGap(123, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(CBbranch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnbrnchrep))
                    .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbrnchrepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbrnchrepActionPerformed
        try{
             DBcon db = DBcon.getInstance();
            Connection con = db.getConnection();
           
                 JasperReport jr = null;
          
             InputStream reportStream = getClass().getClassLoader().getResourceAsStream("reports/FINAL_MARKS_BRANCH.jrxml");

            if (reportStream != null) {
              jr = JasperCompileManager.compileReport(reportStream);
                System.out.println("Report compiled successfully!");
            } else {
                System.out.println("Error: Resource 'reports/FINAL_MARKS_BRANCH.jrxml' not found!");
            }

               // JasperReport jr = JasperCompileManager.compileReport("C:\\Users\\binit\\JaspersoftWorkspace\\MyReports\\FINAL_MARKS_BRANCH.jrxml");
                
                Map<String, Object> parameters = new HashMap<>();
                
                 if(CBbranch.getSelectedItem().toString().equals("Lily Branch-Maharagama")){
                 parameters.put("branch", "LILY BRANCH-MAHARAGAMA"); // Pass the branch parameter
                 }
                 else  if(CBbranch.getSelectedItem().toString().equals("Tulip Branch-Gampaha")){
                 parameters.put("branch", "TULIP BRANCH-GAMPAHA"); // Pass the branch parameter
                 }
                 else if(CBbranch.getSelectedItem().toString().equals("Rose Branch-Negombo")){
                 parameters.put("branch", "ROSE BRANCH-NEGOMBO"); // Pass the branch parameter
                 }
                  else if(CBbranch.getSelectedItem().toString().equals("Araliya Branch-Kandy")){
                 parameters.put("branch", "ARALIYA BRANCH-KANDY"); // Pass the brach parameter
                 }
                 
                 
                //displayng reports
            
                JasperPrint jp = JasperFillManager.fillReport(jr, parameters,con);
                //JasperViewer.viewReport(jp,false);
                 JRViewer viewer=new JRViewer(jp);
                 viewer.setPreferredSize(new java.awt.Dimension(800, 800)); // Set width and height
                 jPanel1.removeAll();
                 jPanel1.setLayout(new BorderLayout());
                 jPanel1.add(viewer, BorderLayout.NORTH);
                 jPanel1.revalidate();
                 jPanel1.repaint();
                       
        }
       catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }//GEN-LAST:event_btnbrnchrepActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        reportViewer rep=new reportViewer();
        rep.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnbackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(branchReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(branchReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(branchReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(branchReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new branchReports().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBbranch;
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnbrnchrep;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
