/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import com.mycompany.studentmanagementsystem.DBcon;
import java.awt.BorderLayout;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.swing.JRViewer;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author binit
 */
public class mnthlyReports extends javax.swing.JFrame {

    /**
     * Creates new form mnthlyReports
     */
    public mnthlyReports() {
        initComponents();
         btnback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back_black.png")));
   

         setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        CBmnth = new javax.swing.JComboBox<>();
        btnrep = new javax.swing.JButton();
        btnback = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 971, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 539, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Select Month");

        CBmnth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        btnrep.setText("View Report");
        btnrep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrepActionPerformed(evt);
            }
        });

        btnback.setBackground(new java.awt.Color(0, 0, 0));
        btnback.setIcon(new javax.swing.ImageIcon("C:\\Users\\binit\\OneDrive\\Desktop\\JAVA -EAD\\CW\\StudentManagementSystem\\src\\main\\java\\Images\\png-transparent-computer-icons-sprite-symbol-github-inc-back-button-angle-ribbon-text-thumbnail (1).png")); // NOI18N
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(276, 276, 276)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CBmnth, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnrep)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(CBmnth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnrep)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnrepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrepActionPerformed
        try{
             DBcon db = DBcon.getInstance();
            Connection con = db.getConnection();
           
                 JasperReport jr = null;
          
             InputStream reportStream = getClass().getClassLoader().getResourceAsStream("reports/MARKS_MONTHLY.jrxml");

            if (reportStream != null) {
              jr = JasperCompileManager.compileReport(reportStream);
                System.out.println("Report compiled successfully!");
            } else {
                System.out.println("Error: Resource 'reports/MARKS_MONTHLY.jrxml' not found!");
            }

                //JasperReport jr = JasperCompileManager.compileReport("C:\\Users\\binit\\JaspersoftWorkspace\\MyReports\\MARKS_MONTHLY.jrxml");
                
                Map<String, Object> parameters = new HashMap<>();
                
                 if(CBmnth.getSelectedItem().toString().equals("January")){
                 parameters.put("month", "JANUARY"); // Pass the month parameter
                 }
                 else  if(CBmnth.getSelectedItem().toString().equals("February")){
                 parameters.put("month", "FEBRUARY"); // Pass the month parameter
                 }
                 else if(CBmnth.getSelectedItem().toString().equals("March")){
                 parameters.put("month", "MARCH"); // Pass the month parameter
                 }
                  else if(CBmnth.getSelectedItem().toString().equals("April")){
                 parameters.put("month", "APRIL"); // Pass the month parameter
                 }
                 else if(CBmnth.getSelectedItem().toString().equals("May")){
                 parameters.put("month", "MAY"); // Pass the month parameter
                 }
                  else if(CBmnth.getSelectedItem().toString().equals("June")){
                 parameters.put("month", "JUNE"); // Pass the month parameter
                 }
                else if(CBmnth.getSelectedItem().toString().equals("July")){
                 parameters.put("month", "JULY"); // Pass the month parameter
                 }
                  else if(CBmnth.getSelectedItem().toString().equals("August")){
                 parameters.put("month", "AUGUST"); // Pass the month parameter
                 }
                  else if(CBmnth.getSelectedItem().toString().equals("September")){
                 parameters.put("month", "SEPTEMBER"); // Pass the month parameter
                 }
                  else if(CBmnth.getSelectedItem().toString().equals("October")){
                 parameters.put("month", "OCTOBER"); // Pass the month parameter
                 }
                  else if(CBmnth.getSelectedItem().toString().equals("November")){
                 parameters.put("month", "NOVEMBER"); // Pass the month parameter
                 }
                 else if(CBmnth.getSelectedItem().toString().equals("December")){
                 parameters.put("month", "DECEMBER"); // Pass the month parameter
                 }
                 
                //displayng reports
            
                JasperPrint jp = JasperFillManager.fillReport(jr, parameters,con);
                //JasperViewer.viewReport(jp,false);
                 JRViewer viewer=new JRViewer(jp);
                 viewer.setPreferredSize(new java.awt.Dimension(800, 800)); // Set width and height
                 jPanel1.removeAll();
                 jPanel1.setLayout(new BorderLayout());
                 jPanel1.add(viewer, BorderLayout.NORTH);
                 jPanel1.revalidate();
                 jPanel1.repaint();
                
//
//           
        }
       catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
    }//GEN-LAST:event_btnrepActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        reportViewer rep=new reportViewer();
        rep.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnbackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mnthlyReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mnthlyReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mnthlyReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mnthlyReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mnthlyReports().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBmnth;
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnrep;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
