/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import com.mycompany.studentmanagementsystem.DBcon;
import com.mycompany.studentmanagementsystem.userSession;
import java.sql.Connection;
import java.sql.*;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import javax.swing.*;
import java.util.Date;
/**
 *
 * @author binit
 */
public class StaffWorkSpace extends javax.swing.JFrame {
    int newad=0;
    int branch_id=0;
    String branch=null;
    
    /**
     * Creates new form StaffWorkSpace
     */
    public StaffWorkSpace() {
        initComponents();
        //setting relative paths fr images
        btnhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png")));
        btnlogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png")));


        setAdmission();
        btnup.setVisible(false);
        
          try{
             DBcon db = DBcon.getInstance();
            Connection con = db.getConnection();
           
            Statement stmt=con.createStatement();
            ResultSet rs=stmt.executeQuery("SELECT branchName FROM branch");
            
            //populating combobox with retrieved branch names
            while(rs.next()){
                CBbranch.addItem(rs.getString("branchName"));
            }
          }
          
            catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "SQL error","error",JOptionPane.ERROR_MESSAGE);
        }
            
            catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Error Occured"+ex.toString(),"error",JOptionPane.ERROR_MESSAGE);
        }
        
        
    }
    public void setAdmissionNo(String admissionNo) {
        txtadmission.setText(admissionNo);
    }

    public void setFname(String fname) {
        txtfname.setText(fname);
    }

    public void setIniname(String ininame) {
        txtinitials.setText(ininame);
    }

    public void setbranchName(String branch) {
       CBbranch.setSelectedItem(branch); 
    }

    public void setDOB(String dob) {

         
         try {
                //  LocalDate object (using yyyy-MM-dd format)
                java.time.LocalDate localDate = java.time.LocalDate.parse(dob);

                // Convert LocalDate to java.sql.Date
                java.sql.Date sqlDate = java.sql.Date.valueOf(localDate);

                // Set the date in the DOB date picker or field
                DOB.setDate(sqlDate);
            } catch (Exception e) {
                // Handle invalid date format
                JOptionPane.showMessageDialog(null, "Invalid date format. Please use yyyy-MM-dd", "Error", JOptionPane.ERROR_MESSAGE);
            }
        
    }

    public void setAddress(String address) {
        txtaddress.setText(address);
    }

    public void setFather(String father) {
        txtfather.setText(father);
    }

    public void setMother(String mother) {
        txtmother.setText(mother);
    }

    public void setTP(String tp) {
        txttele.setText(tp);
    }
    public JButton getaddstudentbtn(){
        return btnadd1;
    }
      public JButton getbtnup(){
        return btnup;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtfname = new javax.swing.JTextField();
        txtinitials = new javax.swing.JTextField();
        txtadmission = new javax.swing.JTextField();
        txtaddress = new javax.swing.JTextField();
        txtmother = new javax.swing.JTextField();
        txttele = new javax.swing.JTextField();
        txtfather = new javax.swing.JTextField();
        btnview = new javax.swing.JButton();
        DOB = new com.toedter.calendar.JDateChooser();
        btnup = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        CBbranch = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        btnlogout = new javax.swing.JButton();
        btnhome = new javax.swing.JButton();
        btnadd1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Add Student Details");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("DOB");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 520, 134, 43));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Admission no");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 134, 43));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Branch");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 164, 43));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Residential Address");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, 134, 43));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Father's Name");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 134, 43));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Telephone No");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 520, 134, 43));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Name with Initials ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 164, 43));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Mother's Name");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 420, 134, 43));

        txtfname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfnameActionPerformed(evt);
            }
        });
        jPanel1.add(txtfname, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 315, 224, 81));

        txtinitials.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtinitialsActionPerformed(evt);
            }
        });
        jPanel1.add(txtinitials, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 435, 224, 34));

        txtadmission.setEditable(false);
        jPanel1.add(txtadmission, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 165, 34));

        txtaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaddressActionPerformed(evt);
            }
        });
        jPanel1.add(txtaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 130, 220, 123));
        jPanel1.add(txtmother, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 420, 224, 34));
        jPanel1.add(txttele, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 530, 224, 34));
        jPanel1.add(txtfather, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 300, 224, 34));

        btnview.setBackground(new java.awt.Color(204, 204, 204));
        btnview.setText("View Student List");
        btnview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewActionPerformed(evt);
            }
        });
        jPanel1.add(btnview, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 620, 138, -1));

        DOB.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(DOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 520, 224, 43));

        btnup.setBackground(new java.awt.Color(204, 204, 204));
        btnup.setText("Update");
        btnup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupActionPerformed(evt);
            }
        });
        jPanel1.add(btnup, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 620, 120, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText(" Student Name In Full");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 164, 43));

        jPanel1.add(CBbranch, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 165, 36));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 850, 10));

        btnlogout.setBackground(new java.awt.Color(0, 0, 0));
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 20, 40, 40));

        btnhome.setBackground(new java.awt.Color(0, 0, 0));
        btnhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomeActionPerformed(evt);
            }
        });
        jPanel1.add(btnhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 40, 40));

        btnadd1.setBackground(new java.awt.Color(204, 204, 204));
        btnadd1.setText("Save");
        btnadd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadd1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnadd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 620, 138, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1024, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaddressActionPerformed

    private void btnviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewActionPerformed
                StaffWorkSpace2 view=new StaffWorkSpace2();
                view.setVisible(true);
                this.setVisible(false);
    }//GEN-LAST:event_btnviewActionPerformed

    private void txtinitialsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtinitialsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtinitialsActionPerformed

    private void btnupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupActionPerformed
        int admission_no=Integer.parseInt(txtadmission.getText());
         branch=CBbranch.getSelectedItem().toString();
        String fname=txtfname.getText();
        String iname=txtinitials.getText();
        String address=txtaddress.getText();
        String fatherName=txtfather.getText();
        String motherName=txtmother.getText();
        String tp=txttele.getText();
        Date selectedDate = DOB.getDate();
        java.sql.Date sqlDate = new java.sql.Date(selectedDate.getTime());
//       
//         // Format the date as a string
//          SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
//          String formattedDate = dateFormat.format(selectedDate);
        
        
//        String DOB=
                
            try{
              DBcon db = DBcon.getInstance();
            Connection con = db.getConnection();
           
             //calling method to retrieve branch_id
            branch_id=getBranchId(branch);
            
            //create statement object
            PreparedStatement prestat=con.prepareStatement("UPDATE student SET branch_id=?,fname=?,iniName=?,DOB=?,Address=?,Father=?,Mother=?,TP=? WHERE admission_no=?");
            prestat.setInt(1, branch_id);
            prestat.setString(2, fname);
            prestat.setString(3,iname);
            prestat.setDate(4, sqlDate);
            prestat.setString(5, address);
            prestat.setString(6, fatherName);
            prestat.setString(7, motherName);
            prestat.setString(8, tp);
            prestat.setInt(9, admission_no);
            
            prestat.executeUpdate();
            
            JOptionPane.showMessageDialog(null,"record updated succeessfully","Information",JOptionPane.INFORMATION_MESSAGE);
            }
           
            catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "SQL error","error",JOptionPane.ERROR_MESSAGE);
        }
            
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Error Occured"+ex.toString(),"error",JOptionPane.ERROR_MESSAGE);
        }
            StaffWorkSpace2 obj=new StaffWorkSpace2();
            obj.fillTableContent();
    }//GEN-LAST:event_btnupActionPerformed

    private void txtfnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfnameActionPerformed

    private void btnhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomeActionPerformed
       String userType=userSession.getInstance().getuUserType();
       if(userType=="Admin"){
        Home_Admin hme=new Home_Admin();
       hme.setVisible(true);
       this.setVisible(false);
       }
       else{
               Home_Teacher hme=new Home_Teacher();
               hme.setVisible(true);
               this.setVisible(false);
               }
       
    }//GEN-LAST:event_btnhomeActionPerformed

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
       loginPage logout=new loginPage();
       logout.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void btnadd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadd1ActionPerformed
            branch=CBbranch.getSelectedItem().toString();
        String fname=txtfname.getText();
        String iname=txtinitials.getText();
        String address=txtaddress.getText();
        String fatherName=txtfather.getText();
        String motherName=txtmother.getText();
        String tp=txttele.getText();
        Date selectedDate = DOB.getDate();
        java.sql.Date sqlDate = new java.sql.Date(selectedDate.getTime());
//       
//         // Format the date as a string
//          SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
//          String formattedDate = dateFormat.format(selectedDate);
        
        

            try{
            DBcon db = DBcon.getInstance();
            Connection con = db.getConnection();
           
            branch=CBbranch.getSelectedItem().toString();

            //calling method to retrieve branch_id
            branch_id=getBranchId(branch);
         
            //create statement object
            PreparedStatement prestat=con.prepareStatement("INSERT INTO student VALUES(?,?,?,?,?,?,?,?,?)");
            prestat.setInt(1, newad);
            prestat.setInt(2, branch_id);
            prestat.setString(3, fname);
            prestat.setString(4,iname);     
            prestat.setDate(5, sqlDate);
            prestat.setString(6, address);
            prestat.setString(7, fatherName);
            prestat.setString(8, motherName);
            prestat.setString(9, tp);
            
            prestat.executeUpdate();
            String[] options={"OK","View"};
            int choice=JOptionPane.showOptionDialog(null,"Record Entered Succeessfully","Information",JOptionPane.DEFAULT_OPTION,JOptionPane.INFORMATION_MESSAGE,null,options,options[0]);
            if(choice==0){
               setAdmission();
                txtfname.setText("");
                txtinitials.setText("");
                DOB.setDate(null);
                txtaddress.setText("");
                txtfather.setText("");
                txtmother.setText("");
                txttele.setText(""); 
            }
            else{
                StaffWorkSpace2 view=new StaffWorkSpace2();
                view.setVisible(true);
                this.setVisible(false);
            }
            }
         catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "SQL error","error",JOptionPane.ERROR_MESSAGE);
        }
        
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Error Occured"+ex.toString(),"error",JOptionPane.ERROR_MESSAGE);
        }
                                             // TODO add your handling code here:
    }//GEN-LAST:event_btnadd1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffWorkSpace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffWorkSpace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffWorkSpace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffWorkSpace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffWorkSpace().setVisible(true);
            }
        });
    }
    
    private void setAdmission(){
         try{
            //regitser the drivers
            Class.forName("com.mysql.cj.jdbc.Driver");
            
            //create the connection
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/studentManagementdb","root","Bini@2004");
            
            //generating admission number
            
            PreparedStatement prestat1=con.prepareStatement("SELECT COALESCE(MAX(admission_no), 999) FROM student");
            ResultSet rs=prestat1.executeQuery();
            
            if(rs.next()){
                
                int lastad=rs.getInt(1);
                newad=lastad+1;
            }
            else{
                newad=1000;     //start frm 1000 if no record exists
            }
            
            txtadmission.setText(String.valueOf(newad));
         
        }
          catch(ClassNotFoundException ex){
            JOptionPane.showMessageDialog(null, "Driver registration unsuccessfull","error",JOptionPane.ERROR_MESSAGE);
        }
            catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "SQL error","error",JOptionPane.ERROR_MESSAGE);
        }
         
    }
    private int getBranchId(String branch){
     
         try{
            //regitser the drivers
            Class.forName("com.mysql.cj.jdbc.Driver");
            
            //create the connection
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/studentManagementdb","root","Bini@2004");
            
            //query to get branch id 
            PreparedStatement prestat1=con.prepareStatement("SELECT branch_id FROM branch where branchName=?");
            prestat1.setString(1, branch);
            ResultSet rs=prestat1.executeQuery();
            
            if (rs.next()) {
                 branch_id = rs.getInt("branch_id");
                // Handle the result
            } else {
                JOptionPane.showMessageDialog(null, "No branch found for the provided name.", "Error", JOptionPane.ERROR_MESSAGE);
            }
           
          
         
    }
           catch(ClassNotFoundException ex){
            JOptionPane.showMessageDialog(null, "Driver registration unsuccessfull","error",JOptionPane.ERROR_MESSAGE);
        }
            catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "SQL error"+ex.toString(),"error",JOptionPane.ERROR_MESSAGE);
        }
           return branch_id;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBbranch;
    private com.toedter.calendar.JDateChooser DOB;
    private javax.swing.JButton btnadd1;
    private javax.swing.JButton btnhome;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnup;
    private javax.swing.JButton btnview;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtadmission;
    private javax.swing.JTextField txtfather;
    private javax.swing.JTextField txtfname;
    private javax.swing.JTextField txtinitials;
    private javax.swing.JTextField txtmother;
    private javax.swing.JTextField txttele;
    // End of variables declaration//GEN-END:variables
}
